name: Daily ServiceNow Ping

on:
  schedule:
  # Runs at 12:00 AM UTC
  - cron: '0 0 * * *'
  # Runs at 12:00 PM UTC
  - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  ping_instance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: List files in repository
      run: ls -R  

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run the keep-alive script
      run: python keep_alive.py
      env:
        SN_CLIENT_ID: ${{ secrets.SN_CLIENT_ID }}
        SN_CLIENT_SECRET: ${{ secrets.SN_CLIENT_SECRET }}
        SN_INSTANCE: ${{ secrets.SN_INSTANCE }}
